### PR TITLE
capture tInfoS field from SAUCE

### PR DESCRIPTION
**Pull request by sjs**

### CODE REVIEW

**Comment by andyherbert** [comment]
Possible issue: This works, but unlike the rest of the text fields, the tInfoS field is a zero-terminated string. So, using this method, the returned string could be something like "IBM VGA\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0" -- which makes it a pain for equivalence checks. I think that the best solution to this would be to implement getSZ(num), which essentially follows the same logic as getS(), but terminates when `0` is encountered. For SAUCE records prior to 00.5, this should result in an empty string.

**Comment by sjs** [comment]
Fixed. :+1:

**Comment by sjs** [comment]
Oh, I completely misunderstood. That's not a function yet. Reverting that last change.

**Comment by andyherbert** [comment]
It's not a problem, if you leave it with me I'll implement it at the same time as the other stuff.

**Comment by sjs** [comment]
Awesome. Thanks!

**Pull request closed without merging**
